### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by ctsstc** [BryceGraves/chutes-and-ladders#51]
I would like to see if current commits are failing or passing the test suite.

Travis CI is a quick implementation for Ruby apps, free for open source, and integrates nicely with Github.

## Acceptance
- [x] Add CI
- [x] Display status in Github

**Comment by BryceGraves** [comment]
I done did it. The read me is real ugly but it's on there.

**Comment by BryceGraves** [comment]
I should probably let you close it since you asked for it and know more about adding it. Is this up to snuff?

**Comment by ctsstc** [comment]
Confirmed looks good, product accepts your sacrifice and offerings.
